### ISSUE TITLE
Bug al buscar mozos que no existen.

### ISSUE THREAD

**Issue by gonzaabel** [ristorantino/ristorantino-vendor#1]
Cuando buscas un mozo y no encuentra ninguno, te sale http://prnt.sc/dzs3qn
como si no existiesen mozos, en vez de salir un mensaje diciendo que no se encontraron mozos con esos criterios de busqueda.

**Comment by alevilar** [comment]
Este issue continua abierto. Habria que hacer un find(count) sin filstros de busqueda y mostrar este mensaje solo cuando el resultado de CERO

**Comment by alevilar** [comment]
cuando no se encuentran mozos, luego de realizar una busqueda, no se visualiza el formulario de busqueda. Se deberia poder verlo

**Comment by gonzaabel** [comment]
Listo, corregido.
