### ISSUE TITLE
Bug: El metodo de activación de cuenta mediante mensaje al correo no funciona adecuadamente

### ISSUE THREAD

**Issue by gonzaabel** [ristorantino/ristorantino-vendor#10]
Si te registras, el correo te llega bien. Pero podes loguearte sin 'activar' la cuenta.
Y si desde la base de datos la desactivas, (con el is_active = 0) al querer loguearte te dice que tus datos son incorrectos en lugar de decir: 'Tu cuenta no esta activada.'

**Comment by alevilar** [comment]
El  is_active = 0 justamente es para marcar si 'Tu cuenta no esta activada.'. Por lo tanto es el comportamiento deseado. Por lo pronto queremos que un usuario se pueda registrar rapidamente, con el correo que quiera, aunque no exista.
