### ISSUE TITLE
Plugin compras. al recepcionar mercaderia con cantidad inferior a la solicitada 

### ISSUE THREAD

**Issue by alevilar** [ristorantino/ristorantino-vendor#17]
Cuando se recepciona mercaderia se puede modificar la cantidad pedida colocando alli la cantidad realmente recibida. Cuando el numero es inferior, al editar, se genera autimaticamente una nueva solicitud de pedido de mercaderia por la diferencia. Pero, en este caso, es necesario que el sistema consulte si se desea generar un pedido, o simplemente editar sin pedir nada mas.

Ejemplo:
Pido 5 Kilos de Bananas, pero me llegan solo 4 Kilos. Entonces al editarlo, el sistema me genera **automaticamente** un nuevo pedido por 1Kilo (la diferencia). 
El ideal es **_no generarlo automaticamente_**, sino consultar al usuario si desea que paxapos lo haga por él, o no. En caso de generar nuevo pedido, que incluso permita editar el nuevi valor.

**Comment by gonzaabel** [comment]
Lo solucionaste? Porque de manera local, en desarrollo y en producción lo probé y funciona bien. No genera otra orden. Simplemente actualiza la cantidad.

**Comment by alevilar** [comment]
no, la verdad que no lo toqué. Agregué el BUG porque me lo habias dicho vos
:D

**Comment by gonzaabel** [comment]
Ok. Ahora anda bien.
