### ISSUE TITLE
En nuevos comercios no te muestra el modulo cajero en la lista de modulos (dashboard)

### ISSUE THREAD

**Issue by gonzaabel** [ristorantino/ristorantino-vendor#9]
Cuando vas a la administración de agregar/quitar APPs no te muestra el cajero en la lista de modulos aunque lo tengas tildado. Desde el modulo salón se lo puede usar y funciona bien.

**Comment by alevilar** [comment]
solucionado en comit d9d5a39e6187c46943cdd0e2b9531dc18e639648 del Plugin Install
